name: Build & Deploy (pygbag → GitHub Pages)

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pygame-ce pygbag

      - name: Build with pygbag and enable autorun
        run: |
          python -m pygbag --build --archive --ume_block 0 main.py
          # Force autorun to 1 so game starts automatically
          sed -i 's/autorun : 0/autorun : 1/g' build/web/index.html

      - name: Ensure assets are in build/web
        run: |
          echo "=== Copying assets to build/web ==="
          
          # Create directories if they don't exist
          mkdir -p build/web/assets
          mkdir -p build/web/sounds
          
          # Copy entire assets folder
          if [ -d "assets" ]; then
            cp -rv assets/* build/web/assets/ || true
            echo "✓ Copied assets folder"
          fi
          
          # Copy entire sounds folder
          if [ -d "sounds" ]; then
            cp -rv sounds/* build/web/sounds/ || true
            echo "✓ Copied sounds folder"
          fi
          
          # Also copy sound_effects.py to build
          if [ -f "sound_effects.py" ]; then
            cp -v sound_effects.py build/web/ || true
            echo "✓ Copied sound_effects.py"
          fi
          
          echo ""
          echo "=== Final build/web structure ==="
          find build/web -type f -name "*.png" -o -name "*.ogg" -o -name "*.ttf" -o -name "*.py" | sort
          echo ""
          echo "=== Verify critical files ==="
          test -f build/web/assets/flappybirdbg.png && echo "✓ Background" || echo "✗ Background missing"
          test -f build/web/assets/flappybird.png && echo "✓ Bird" || echo "✗ Bird missing"
          test -f build/web/assets/PressStart2P.ttf && echo "✓ Font" || echo "✗ Font missing"
          test -d build/web/sounds && echo "✓ Sounds folder" || echo "✗ Sounds folder missing"

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4